#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "Running frontend lint..."
cd frontend || exit 1
npm run lint || exit 1
cd ..

echo "Running backend checks..."
cd backend || exit 1

# Install dependencies
pip install -r requirements.txt || exit 1

# Run Black with venv excluded
black . --exclude 'venv' || exit 1

# Run Flake8 with venv excluded
flake8 . --exclude=venv || exit 1

cd ..
